-- Auto-generated by scripts/build_parts_equivalences.py
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Akyoto', 'AKD26420', 'Pastillas de freno Akyoto AKD26420' FROM spare_parts WHERE referencia_interna = '04465-26420'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NIBK', 'PN1516', 'Pastillas de freno NIBK PN1516' FROM spare_parts WHERE referencia_interna = '04465-26420'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'GDB7579', 'Pastillas de freno TRW GDB7579' FROM spare_parts WHERE referencia_interna = '04465-26420'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '190500-2240', 'Sensor de posición cigüeñal Denso 190500-2240' FROM spare_parts WHERE referencia_interna = '10FCA-00518-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NGK', '70098', 'Sensor de posición cigüeñal NGK 70098' FROM spare_parts WHERE referencia_interna = '10FCA-00518-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Standard Motor Products', 'PC640', 'Sensor de posición cigüeñal SMP PC640' FROM spare_parts WHERE referencia_interna = '10FCA-00518-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bosch', '15733', 'Sensor de oxígeno Bosch 15733' FROM spare_parts WHERE referencia_interna = '10FCA-08524-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '234-9006', 'Sensor de oxígeno Denso 234-9006' FROM spare_parts WHERE referencia_interna = '10FCA-08524-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NGK', 'OZA669-EC3', 'Sensor de oxígeno NGK OZA669-EC3' FROM spare_parts WHERE referencia_interna = '10FCA-08524-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '12204-0C030', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '10FCA-14507-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '196300-2010', 'Sensor de posición árbol de levas Denso 196300-2010' FROM spare_parts WHERE referencia_interna = '10FCA-14509-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NGK', '94472', 'Sensor de posición árbol de levas NGK 94472' FROM spare_parts WHERE referencia_interna = '10FCA-14509-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Standard Motor Products', 'PC492', 'Sensor de posición árbol de levas SMP PC492' FROM spare_parts WHERE referencia_interna = '10FCA-14509-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Aisin', 'PMP-0152', 'Bomba de dirección Aisin PMP-0152' FROM spare_parts WHERE referencia_interna = '10FCA-21512-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Cardone', '206605', 'Bomba de dirección Cardone 206605 (exchange)' FROM spare_parts WHERE referencia_interna = '10FCA-21512-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'JPR173', 'Bomba de dirección TRW JPR173' FROM spare_parts WHERE referencia_interna = '10FCA-21512-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Beck Arnley', '178-7495', 'Bobina de encendido Beck Arnley 178-7495' FROM spare_parts WHERE referencia_interna = '11FCA-04501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '673-1303', 'Bobina de encendido Denso 673-1303' FROM spare_parts WHERE referencia_interna = '11FCA-04501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NGK', 'U5039', 'Bobina de encendido NGK U5039' FROM spare_parts WHERE referencia_interna = '11FCA-04501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', 'FK20HR11', 'Bujía iridium Denso FK20HR11' FROM spare_parts WHERE referencia_interna = '11FCA-04505-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', 'SKJ20DR-M11', 'Bujía iridium Denso SKJ20DR-M11' FROM spare_parts WHERE referencia_interna = '11FCA-04505-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NGK', 'LFR5AIX-11', 'Bujía iridium NGK LFR5AIX-11' FROM spare_parts WHERE referencia_interna = '11FCA-04505-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Hengst', 'E309L09', 'Filtro de aire equivalente Hengst E309L09' FROM spare_parts WHERE referencia_interna = '11FCC-09010-C2'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Mahle', 'LX3805', 'Filtro de aire equivalente Mahle LX3805' FROM spare_parts WHERE referencia_interna = '11FCC-09010-C2'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'WIX', 'WA10829', 'Filtro de aire equivalente WIX WA10829' FROM spare_parts WHERE referencia_interna = '11FCC-09010-C2'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Baldwin', 'BF7534', 'Filtro de combustible equivalente Baldwin BF7534' FROM spare_parts WHERE referencia_interna = '11Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Mahle', 'KL145', 'Filtro de combustible equivalente Mahle KL145' FROM spare_parts WHERE referencia_interna = '11Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'WIX', 'WL7401', 'Filtro de combustible equivalente WIX WL7401' FROM spare_parts WHERE referencia_interna = '11Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Gates', 'TH26819', 'Termostato Gates TH26819' FROM spare_parts WHERE referencia_interna = '133TZ-06501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Mahle', 'TH26819', 'Termostato Mahle TH26819' FROM spare_parts WHERE referencia_interna = '133TZ-06501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Vemo', 'V20-67-0073', 'Termostato Vemo V20-67-0073' FROM spare_parts WHERE referencia_interna = '133TZ-06501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'AISIN', 'WPT-168V', 'Bomba de agua AISIN WPT-168V' FROM spare_parts WHERE referencia_interna = '13FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'GRAF', 'PA1080', 'Bomba de agua GRAF PA1080' FROM spare_parts WHERE referencia_interna = '13FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'KAMOKA', 'T0267', 'Bomba de agua KAMOKA T0267' FROM spare_parts WHERE referencia_interna = '13FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'LuK', '624-0310', 'Kit de embrague LuK 624-0310' FROM spare_parts WHERE referencia_interna = '16FCA-00501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sachs', '3000960001', 'Kit de embrague Sachs 3000 960 001' FROM spare_parts WHERE referencia_interna = '16FCA-00501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Valeo', '826793', 'Kit de embrague Valeo 826793' FROM spare_parts WHERE referencia_interna = '16FCA-00501-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'LuK', '624-0310', 'Kit de embrague LuK 624-0310' FROM spare_parts WHERE referencia_interna = '16FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sachs', '3000960001', 'Kit de embrague Sachs 3000 960 001' FROM spare_parts WHERE referencia_interna = '16FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Valeo', '826793', 'Kit de embrague Valeo 826793' FROM spare_parts WHERE referencia_interna = '16FCA-00502-200'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'AISIN', 'CST-023', 'Cilindro de embrague AISIN CST-023' FROM spare_parts WHERE referencia_interna = '16FCU-04020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'LuK', '535-0200', 'Cilindro de embrague LuK 535-0200' FROM spare_parts WHERE referencia_interna = '16FCU-04020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'PSC65', 'Cilindro de embrague TRW PSC65' FROM spare_parts WHERE referencia_interna = '16FCU-04020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'AISIN', 'CMT-048', 'Bomba de embrague AISIN CMT-048' FROM spare_parts WHERE referencia_interna = '16Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'LuK', '520-0350', 'Bomba de embrague LuK 520-0350' FROM spare_parts WHERE referencia_interna = '16Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'PMF598', 'Bomba de embrague TRW PMF598' FROM spare_parts WHERE referencia_interna = '16Z15-05010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Exedy', 'RB-C2012-SA314', 'Collarín de embrague Exedy RB-C2012-SA314' FROM spare_parts WHERE referencia_interna = '170GD-00503'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'LuK', '602-0310', 'Collarín de embrague LuK 602-0310' FROM spare_parts WHERE referencia_interna = '170GD-00503'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Valeo', '826793', 'Collarín de embrague Valeo 826793' FROM spare_parts WHERE referencia_interna = '170GD-00503'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '33530-26240', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '17FC2-03025'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Dormann', '15232', 'Cable de transmisión Dormann 15232' FROM spare_parts WHERE referencia_interna = '17FC2-03065'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febi', '49732', 'Cable de transmisión Febi 49732' FROM spare_parts WHERE referencia_interna = '17FC2-03065'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TSK', '33820-26280', 'Cable de transmisión TSK 33820-26280' FROM spare_parts WHERE referencia_interna = '17FC2-03065'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Blue Print', 'ADT34710', 'Tambor de freno Blue Print ADT34710' FROM spare_parts WHERE referencia_interna = '24FC1-00512'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Brembo', '14.5163.10', 'Tambor de freno Brembo 14.5163.10' FROM spare_parts WHERE referencia_interna = '24FC1-00512'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'DF4242', 'Tambor de freno TRW DF4242' FROM spare_parts WHERE referencia_interna = '24FC1-00512'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '42421-26030', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '24FC1-00558'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'KOYO', 'BR303320D', 'Pista de maza KOYO BR303320D' FROM spare_parts WHERE referencia_interna = '24FC1-00562'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'NTN', 'LM102949/LM102910', 'Pista de maza NTN LM102949/LM102910' FROM spare_parts WHERE referencia_interna = '24FC1-00562'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'SKF', 'BR303320', 'Pista de maza SKF BR303320' FROM spare_parts WHERE referencia_interna = '24FC1-00562'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '43517-35010', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '24FC1-00563'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febest', '0282-TRH200R', 'Semieje Febest 0282-TRH200R' FROM spare_parts WHERE referencia_interna = '24FC1-00571'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'GSP', 'NC11198', 'Semieje GSP NC11198' FROM spare_parts WHERE referencia_interna = '24FC1-00571'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TrakMotive', 'TO-8034', 'Semieje TrakMotive TO-8034' FROM spare_parts WHERE referencia_interna = '24FC1-00571'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Aisin', 'BKH-0004', 'Kit de ajustadores Aisin BKH-0004' FROM spare_parts WHERE referencia_interna = '24FCC-00502-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febi', '25388', 'Kit de ajustadores Febi 25388' FROM spare_parts WHERE referencia_interna = '24FCC-00502-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'KSP266', 'Kit de ajustadores TRW KSP266' FROM spare_parts WHERE referencia_interna = '24FCC-00502-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bendix', '2289', 'Balatas Bendix 2289' FROM spare_parts WHERE referencia_interna = '24FCC-00701-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Brembo', 'S24 508', 'Balatas Brembo S24 508' FROM spare_parts WHERE referencia_interna = '24FCC-00701-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'GSP2147T', 'Balatas TRW GSP2147T' FROM spare_parts WHERE referencia_interna = '24FCC-00701-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sin proveedor', '', 'Sin equivalente aftermarket y sin referencia Toyota' FROM spare_parts WHERE referencia_interna = '29Z15-02131-A'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '48046-26130', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '29Z15-02502'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '48162-26520', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '29Z15-15001'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Ashika', 'MA-20096', 'Amortiguador trasero Ashika MA-20096' FROM spare_parts WHERE referencia_interna = '29Z15-21020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'KYB', '344204', 'Amortiguador trasero KYB 344204' FROM spare_parts WHERE referencia_interna = '29Z15-21020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sachs', '317169', 'Amortiguador trasero Sachs 317 169' FROM spare_parts WHERE referencia_interna = '29Z15-21020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '48067-29215', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '29Z15-25010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '48067-29215', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '29Z15-25020'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febi', '48226', 'Rótula Pitman Febi 48226' FROM spare_parts WHERE referencia_interna = '29Z15-25050'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'MOOG', 'TO-BJ-15985', 'Rótula Pitman Moog TO-BJ-15985' FROM spare_parts WHERE referencia_interna = '29Z15-25050'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'JBJ7551', 'Rótula Pitman TRW JBJ7551' FROM spare_parts WHERE referencia_interna = '29Z15-25050'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, '555 Japan', 'SC8095L', 'Mango dirección izquierdo 555 Japan SC8095L' FROM spare_parts WHERE referencia_interna = '29Z15-25501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'MOOG', 'EV80050', 'Mango dirección izquierdo Moog EV80050' FROM spare_parts WHERE referencia_interna = '29Z15-25501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'TIS509', 'Mango dirección izquierdo TRW TIS509' FROM spare_parts WHERE referencia_interna = '29Z15-25501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, '555 Japan', 'SC8095R', 'Mango dirección derecho 555 Japan SC8095R' FROM spare_parts WHERE referencia_interna = '29Z15-25502'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'MOOG', 'EV80051', 'Mango dirección derecho Moog EV80051' FROM spare_parts WHERE referencia_interna = '29Z15-25502'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'TIS508', 'Mango dirección derecho TRW TIS508' FROM spare_parts WHERE referencia_interna = '29Z15-25502'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'FAG', '713621130', 'Rodamiento de rueda FAG 713 6211 30' FROM spare_parts WHERE referencia_interna = '29Z15-25508'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'OPTIMAL', '981846', 'Rodamiento de rueda Optimal 981846' FROM spare_parts WHERE referencia_interna = '29Z15-25508'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'SKF', 'VKBA7497', 'Rodamiento de rueda SKF VKBA 7497' FROM spare_parts WHERE referencia_interna = '29Z15-25508'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bosch', '0986479R27', 'Disco de freno Bosch 0 986 479 R27' FROM spare_parts WHERE referencia_interna = '29Z15-25511'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Brembo', '09.B063.10', 'Disco de freno Brembo 09.B063.10' FROM spare_parts WHERE referencia_interna = '29Z15-25511'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'DF6481', 'Disco de freno TRW DF6481' FROM spare_parts WHERE referencia_interna = '29Z15-25511'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sin proveedor', '', 'Sin equivalente aftermarket y sin referencia Toyota' FROM spare_parts WHERE referencia_interna = '29Z15-25538'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Lemförder', '28860 01', 'Barra estabilizadora Lemförder 28860 01' FROM spare_parts WHERE referencia_interna = '29Z15-25543'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'MOOG', 'K200856', 'Barra estabilizadora Moog K200856' FROM spare_parts WHERE referencia_interna = '29Z15-25543'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'JAR1159', 'Barra estabilizadora TRW JAR1159' FROM spare_parts WHERE referencia_interna = '29Z15-25543'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febi', '33594', 'Tope de suspensión Febi 33594' FROM spare_parts WHERE referencia_interna = '29Z15-25559'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'KYB', 'SM5581', 'Tope de suspensión KYB SM5581' FROM spare_parts WHERE referencia_interna = '29Z15-25559'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sachs', '817817', 'Tope de suspensión Sachs 817817' FROM spare_parts WHERE referencia_interna = '29Z15-25559'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Toyota OEM', '48661-26050', 'Requiere pieza OEM o sin equivalente aftermarket' FROM spare_parts WHERE referencia_interna = '29Z15-25563'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Febest', '01110-016F', 'Amortiguador delantero Febest 01110-016F' FROM spare_parts WHERE referencia_interna = '29Z15-25619'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'KYB', '344493', 'Amortiguador delantero KYB 344493' FROM spare_parts WHERE referencia_interna = '29Z15-25619'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Sachs', '315016', 'Amortiguador delantero Sachs 315 016' FROM spare_parts WHERE referencia_interna = '29Z15-25619'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bendix', 'MKD533U', 'Pastillas de freno Bendix MKD533U' FROM spare_parts WHERE referencia_interna = '30Z15-00011'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Jurid', '750-650731', 'Pastillas de freno Jurid 750-650731' FROM spare_parts WHERE referencia_interna = '30Z15-00011'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'GDB1763', 'Pastillas de freno TRW GDB1763' FROM spare_parts WHERE referencia_interna = '30Z15-00011'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Aisin', 'CBR-0713', 'Caliper Aisin CBR-0713 (remanufacturado)' FROM spare_parts WHERE referencia_interna = '30Z15-00015'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Cardone', '18-9809', 'Caliper Cardone 18-9809 (nuevo)' FROM spare_parts WHERE referencia_interna = '30Z15-00015'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'CBR1423', 'Caliper TRW CBR1423 (remanufacturado)' FROM spare_parts WHERE referencia_interna = '30Z15-00015'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Aisin', 'CHP-0047', 'Cremallera de dirección Aisin CHP-0047 (exchange)' FROM spare_parts WHERE referencia_interna = '34FC1-01010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Cardone', '26-2672', 'Cremallera de dirección Cardone 26-2672 (remanufacturado)' FROM spare_parts WHERE referencia_interna = '34FC1-01010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'RSP1789', 'Cremallera de dirección TRW RSP1789 (exchange)' FROM spare_parts WHERE referencia_interna = '34FC1-01010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'AISIN', 'BMT-072', 'Cilindro maestro de frenos AISIN BMT-072' FROM spare_parts WHERE referencia_interna = '35FCC-51010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bosch', 'F026T02503', 'Cilindro maestro de frenos Bosch F026T02503' FROM spare_parts WHERE referencia_interna = '35FCC-51010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'TRW', 'BMF1082', 'Cilindro maestro de frenos TRW BMF1082' FROM spare_parts WHERE referencia_interna = '35FCC-51010'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '104210-4280', 'Alternador Denso 104210-4280' FROM spare_parts WHERE referencia_interna = '373TZ-01501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '104210-4281', 'Alternador Denso 104210-4281' FROM spare_parts WHERE referencia_interna = '373TZ-01501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'PSH', '195.953.130', 'Alternador PSH 195.953.130' FROM spare_parts WHERE referencia_interna = '373TZ-01501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bosch', 'SR440X', 'Motor de arranque Bosch SR440X' FROM spare_parts WHERE referencia_interna = '373TZ-08501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Denso', '100211-7240', 'Motor de arranque Denso 100211-7240' FROM spare_parts WHERE referencia_interna = '373TZ-08501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Remy', '16895', 'Motor de arranque Remy 16895' FROM spare_parts WHERE referencia_interna = '373TZ-08501'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bosch', '0986AF0273', 'Filtro de aceite equivalente Bosch 0986AF0273' FROM spare_parts WHERE referencia_interna = '90915-YZZE1'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Fram', 'PH4967', 'Filtro de aceite equivalente Fram PH4967' FROM spare_parts WHERE referencia_interna = '90915-YZZE1'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Mann-Filter', 'W68/3', 'Filtro de aceite equivalente Mann W68/3' FROM spare_parts WHERE referencia_interna = '90915-YZZE1'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'ACDelco', '3K340', 'Correa ACDelco 3K340' FROM spare_parts WHERE referencia_interna = '90916-02570'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Bando', '3PK865', 'Correa Bando 3PK865' FROM spare_parts WHERE referencia_interna = '90916-02570'
ON CONFLICT DO NOTHING;
INSERT INTO part_equivalences (spare_part_id, provider_name, provider_part_number, provider_description)
SELECT refaccion_id, 'Gates', 'K030340', 'Correa Gates K030340' FROM spare_parts WHERE referencia_interna = '90916-02570'
ON CONFLICT DO NOTHING;
